# Generated by Django 4.2.10 on 2024-03-07 13:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=100)),
                ('s_phone', models.BigIntegerField()),
                ('s_entry_date', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
